services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: no  # Prevent auto-start
    environment:
      POSTGRES_USER: admin       # Default username
      POSTGRES_PASSWORD: password  # Default password
      POSTGRES_DB: my_database    # Default database name
    ports:
      - 5432:5432  # Expose PostgreSQL on host's port 5432
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: no  # Prevent auto-start
    ports:
      - 8080:8080  # Expose Adminer on host's port 8080
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge  # Custom bridge network for communication between services

volumes:
  postgres-data:  # Define a volume for PostgreSQL data
