services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: no  # Prevent auto-start
    ports:
      - 3306:3306  # Expose MySQL on host's port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # root password
      MYSQL_DATABASE: my_database         # default database
      MYSQL_USER: admin                   # default user
      MYSQL_PASSWORD: password            # default user's password
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data on the host machine
    networks:
      - mysql-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: no  # Prevent auto-start
    ports:
      - 8080:8080  # Expose Adminer on host's port 8080
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge  # Custom bridge network for communication between services

volumes:
  mysql-data:  # Define a volume for MySQL data
