services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    restart: always
    ports:
      - 6379:6379  # Expose Redis on host's port 6379
    networks:
      - redis-network
    volumes:
      - redis-data:/data  # Persist Redis data on the host machine

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - 5540:5540  # Expose RedisInsight on host's port 5540
    networks:
      - redis-network
    volumes:
      - redisinsight-data:/db # Persist RedisInsight data on the host machine

networks:
  redis-network:
    driver: bridge  # Custom bridge network for communication between services

volumes:
  redis-data:  # Define a volume for Redis data
  redisinsight-data:  # Define a volume for RedisInsight data
